[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.pip",
  "gcc"
]

[phases.install]
cmds = [
  "python -V",
  "pip --version",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
