[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = [
  "python -V",
  "python -m ensurepip",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
