[phases.setup]
nixPkgs = [
  "python310",
  "python310Packages.virtualenv",
  "gcc"
]

[phases.install]
cmds = [
  "python -V",
  "python -m venv /app/venv",
  "source /app/venv/bin/activate && pip install --upgrade pip",
  "source /app/venv/bin/activate && pip install -r requirements.txt"
]

[start]
cmd = "source /app/venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT"
